#include <stdint.h>
#include <libc.h>

#define BACKGROUND_COLOR        0x0305
#define BACKGROUND2_COLOR       0x406
#define SNAKE1_COLOR            0x04C0
#define SNAKE2_COLOR            0x040C
#define TONGUE_COLOR            0x0F00
#define POINTS_COLOR            0x0F00
#define ALPHA_MASK              0xF000
#define EYE_COLOR               0x0CC7
#define PIXELS_BLOCK_X          16
#define PIXELS_BLOCK_Y          16
#define BLOCKS_X                60
#define BLOCKS_Y                40

#define DIR_S                   ((int8_t) 1)  // 0b00000001
#define DIR_E                   ((int8_t) 2)  // 0b00000010
#define DIR_N                   ((int8_t) -1) // 0b11111111
#define DIR_W                   ((int8_t) -2) // 0b11111110

#define MAX_SNAKE_SIZE          512
#define TICKS_PER_FRAME         2
#define START_LEN               5

#define TEXTURE_COMPACT_X       2
#define TEXTURE_COMPACT_Y       2

#define TEXTURE_SIZE_X          (PIXELS_BLOCK_X / TEXTURE_COMPACT_X)
#define TEXTURE_SIZE_Y          (PIXELS_BLOCK_Y / TEXTURE_COMPACT_Y)

static const uint16_t texture_background[TEXTURE_SIZE_X][TEXTURE_SIZE_Y] = {  

    { BACKGROUND_COLOR,  BACKGROUND2_COLOR, BACKGROUND_COLOR,  BACKGROUND2_COLOR, BACKGROUND_COLOR,  BACKGROUND2_COLOR, BACKGROUND_COLOR,  BACKGROUND2_COLOR },
    { BACKGROUND2_COLOR, BACKGROUND_COLOR,  BACKGROUND2_COLOR, BACKGROUND_COLOR,  BACKGROUND2_COLOR, BACKGROUND_COLOR,  BACKGROUND2_COLOR, BACKGROUND_COLOR },
    { BACKGROUND_COLOR,  BACKGROUND2_COLOR, BACKGROUND_COLOR,  BACKGROUND2_COLOR, BACKGROUND_COLOR,  BACKGROUND2_COLOR, BACKGROUND_COLOR,  BACKGROUND2_COLOR },
    { BACKGROUND2_COLOR, BACKGROUND_COLOR,  BACKGROUND2_COLOR, BACKGROUND_COLOR,  BACKGROUND2_COLOR, BACKGROUND_COLOR,  BACKGROUND2_COLOR, BACKGROUND_COLOR },
    { BACKGROUND_COLOR,  BACKGROUND2_COLOR, BACKGROUND_COLOR,  BACKGROUND2_COLOR, BACKGROUND_COLOR,  BACKGROUND2_COLOR, BACKGROUND_COLOR,  BACKGROUND2_COLOR },
    { BACKGROUND2_COLOR, BACKGROUND_COLOR,  BACKGROUND2_COLOR, BACKGROUND_COLOR,  BACKGROUND2_COLOR, BACKGROUND_COLOR,  BACKGROUND2_COLOR, BACKGROUND_COLOR },
    { BACKGROUND_COLOR,  BACKGROUND2_COLOR, BACKGROUND_COLOR,  BACKGROUND2_COLOR, BACKGROUND_COLOR,  BACKGROUND2_COLOR, BACKGROUND_COLOR,  BACKGROUND2_COLOR },
    { BACKGROUND2_COLOR, BACKGROUND_COLOR,  BACKGROUND2_COLOR, BACKGROUND_COLOR,  BACKGROUND2_COLOR, BACKGROUND_COLOR,  BACKGROUND2_COLOR, BACKGROUND_COLOR }
};

static const uint16_t texture_head_snake1[TEXTURE_SIZE_X][TEXTURE_SIZE_Y] = {  

    { ALPHA_MASK,   ALPHA_MASK,   ALPHA_MASK,   TONGUE_COLOR, ALPHA_MASK,   ALPHA_MASK,   ALPHA_MASK,   ALPHA_MASK   },
    { ALPHA_MASK,   ALPHA_MASK,   ALPHA_MASK,   ALPHA_MASK,   TONGUE_COLOR, ALPHA_MASK,   ALPHA_MASK,   ALPHA_MASK   },
    { ALPHA_MASK,   SNAKE1_COLOR, EYE_COLOR,    TONGUE_COLOR, SNAKE1_COLOR, EYE_COLOR,    SNAKE1_COLOR, ALPHA_MASK   },
    { ALPHA_MASK,   SNAKE1_COLOR, EYE_COLOR,    SNAKE1_COLOR, TONGUE_COLOR, EYE_COLOR,    SNAKE1_COLOR, ALPHA_MASK   },
    { SNAKE1_COLOR, SNAKE1_COLOR, EYE_COLOR,    SNAKE1_COLOR, SNAKE1_COLOR, EYE_COLOR,    SNAKE1_COLOR, SNAKE1_COLOR },
    { SNAKE1_COLOR, SNAKE1_COLOR, SNAKE1_COLOR, SNAKE1_COLOR, SNAKE1_COLOR, SNAKE1_COLOR, SNAKE1_COLOR, SNAKE1_COLOR },
    { SNAKE1_COLOR, SNAKE1_COLOR, SNAKE1_COLOR, SNAKE1_COLOR, SNAKE1_COLOR, SNAKE1_COLOR, SNAKE1_COLOR, SNAKE1_COLOR },
    { SNAKE1_COLOR, SNAKE1_COLOR, SNAKE1_COLOR, SNAKE1_COLOR, SNAKE1_COLOR, SNAKE1_COLOR, SNAKE1_COLOR, SNAKE1_COLOR }
};

static const uint16_t texture_body_snake1[TEXTURE_SIZE_X][TEXTURE_SIZE_Y] = {  

    { ALPHA_MASK,   SNAKE1_COLOR, SNAKE1_COLOR, SNAKE1_COLOR, SNAKE1_COLOR, SNAKE1_COLOR, SNAKE1_COLOR, ALPHA_MASK   },
    { ALPHA_MASK,   SNAKE1_COLOR, SNAKE1_COLOR, SNAKE1_COLOR, SNAKE1_COLOR, SNAKE1_COLOR, SNAKE1_COLOR, ALPHA_MASK   },
    { ALPHA_MASK,   ALPHA_MASK,   SNAKE1_COLOR, SNAKE1_COLOR, SNAKE1_COLOR, SNAKE1_COLOR, SNAKE1_COLOR, SNAKE1_COLOR },
    { ALPHA_MASK,   ALPHA_MASK,   SNAKE1_COLOR, SNAKE1_COLOR, SNAKE1_COLOR, SNAKE1_COLOR, SNAKE1_COLOR, SNAKE1_COLOR },
    { ALPHA_MASK,   SNAKE1_COLOR, SNAKE1_COLOR, SNAKE1_COLOR, SNAKE1_COLOR, SNAKE1_COLOR, SNAKE1_COLOR, ALPHA_MASK   },
    { ALPHA_MASK,   SNAKE1_COLOR, SNAKE1_COLOR, SNAKE1_COLOR, SNAKE1_COLOR, SNAKE1_COLOR, SNAKE1_COLOR, ALPHA_MASK   },
    { SNAKE1_COLOR, SNAKE1_COLOR, SNAKE1_COLOR, SNAKE1_COLOR, SNAKE1_COLOR, SNAKE1_COLOR, ALPHA_MASK,   ALPHA_MASK   },
    { SNAKE1_COLOR, SNAKE1_COLOR, SNAKE1_COLOR, SNAKE1_COLOR, SNAKE1_COLOR, SNAKE1_COLOR, ALPHA_MASK,   ALPHA_MASK   }
};

static const uint16_t texture_twist1_snake1[TEXTURE_SIZE_X][TEXTURE_SIZE_Y] = {  
    { ALPHA_MASK,   ALPHA_MASK,   ALPHA_MASK,   ALPHA_MASK,   ALPHA_MASK,   ALPHA_MASK,   SNAKE1_COLOR, SNAKE1_COLOR },
    { ALPHA_MASK,   ALPHA_MASK,   ALPHA_MASK,   ALPHA_MASK,   ALPHA_MASK,   SNAKE1_COLOR, SNAKE1_COLOR, SNAKE1_COLOR },
    { ALPHA_MASK,   ALPHA_MASK,   ALPHA_MASK,   ALPHA_MASK,   SNAKE1_COLOR, SNAKE1_COLOR, SNAKE1_COLOR, SNAKE1_COLOR },
    { ALPHA_MASK,   ALPHA_MASK,   ALPHA_MASK,   SNAKE1_COLOR, SNAKE1_COLOR, SNAKE1_COLOR, SNAKE1_COLOR, SNAKE1_COLOR },
    { ALPHA_MASK,   ALPHA_MASK,   SNAKE1_COLOR, SNAKE1_COLOR, SNAKE1_COLOR, SNAKE1_COLOR, SNAKE1_COLOR, SNAKE1_COLOR },
    { ALPHA_MASK,   SNAKE1_COLOR, SNAKE1_COLOR, SNAKE1_COLOR, SNAKE1_COLOR, SNAKE1_COLOR, SNAKE1_COLOR, SNAKE1_COLOR },
    { SNAKE1_COLOR, SNAKE1_COLOR, SNAKE1_COLOR, SNAKE1_COLOR, SNAKE1_COLOR, SNAKE1_COLOR, SNAKE1_COLOR, ALPHA_MASK   },
    { SNAKE1_COLOR, SNAKE1_COLOR, SNAKE1_COLOR, SNAKE1_COLOR, SNAKE1_COLOR, SNAKE1_COLOR, SNAKE1_COLOR, ALPHA_MASK   }
};

static const uint16_t texture_twist2_snake1[TEXTURE_SIZE_X][TEXTURE_SIZE_Y] = {  
    { ALPHA_MASK,   SNAKE1_COLOR, ALPHA_MASK,   ALPHA_MASK,   ALPHA_MASK,   ALPHA_MASK,   ALPHA_MASK,   ALPHA_MASK   },
    { SNAKE1_COLOR, SNAKE1_COLOR, SNAKE1_COLOR, ALPHA_MASK,   ALPHA_MASK,   ALPHA_MASK,   ALPHA_MASK,   ALPHA_MASK   },
    { SNAKE1_COLOR, SNAKE1_COLOR, SNAKE1_COLOR, SNAKE1_COLOR, ALPHA_MASK,   ALPHA_MASK,   ALPHA_MASK,   ALPHA_MASK   },
    { SNAKE1_COLOR, SNAKE1_COLOR, SNAKE1_COLOR, SNAKE1_COLOR, SNAKE1_COLOR, ALPHA_MASK,   ALPHA_MASK,   ALPHA_MASK   },
    { SNAKE1_COLOR, SNAKE1_COLOR, SNAKE1_COLOR, SNAKE1_COLOR, SNAKE1_COLOR, SNAKE1_COLOR, ALPHA_MASK,   ALPHA_MASK   },
    { SNAKE1_COLOR, SNAKE1_COLOR, SNAKE1_COLOR, SNAKE1_COLOR, SNAKE1_COLOR, SNAKE1_COLOR, SNAKE1_COLOR, ALPHA_MASK   },
    { SNAKE1_COLOR, SNAKE1_COLOR, SNAKE1_COLOR, SNAKE1_COLOR, SNAKE1_COLOR, SNAKE1_COLOR, SNAKE1_COLOR, ALPHA_MASK   },
    { SNAKE1_COLOR, SNAKE1_COLOR, SNAKE1_COLOR, SNAKE1_COLOR, SNAKE1_COLOR, SNAKE1_COLOR, ALPHA_MASK,   ALPHA_MASK   }
};

static const uint16_t texture_tail_snake1[TEXTURE_SIZE_X][TEXTURE_SIZE_Y] = {  

    { SNAKE1_COLOR, SNAKE1_COLOR, SNAKE1_COLOR, SNAKE1_COLOR, SNAKE1_COLOR, SNAKE1_COLOR, SNAKE1_COLOR, SNAKE1_COLOR },
    { SNAKE1_COLOR, SNAKE1_COLOR, SNAKE1_COLOR, SNAKE1_COLOR, SNAKE1_COLOR, SNAKE1_COLOR, SNAKE1_COLOR, SNAKE1_COLOR },
    { ALPHA_MASK,   SNAKE1_COLOR, SNAKE1_COLOR, SNAKE1_COLOR, SNAKE1_COLOR, SNAKE1_COLOR, SNAKE1_COLOR, ALPHA_MASK   },
    { ALPHA_MASK,   SNAKE1_COLOR, SNAKE1_COLOR, SNAKE1_COLOR, SNAKE1_COLOR, SNAKE1_COLOR, SNAKE1_COLOR, ALPHA_MASK   },
    { ALPHA_MASK,   ALPHA_MASK,   SNAKE1_COLOR, SNAKE1_COLOR, SNAKE1_COLOR, SNAKE1_COLOR, ALPHA_MASK,   ALPHA_MASK   },
    { ALPHA_MASK,   ALPHA_MASK,   SNAKE1_COLOR, SNAKE1_COLOR, SNAKE1_COLOR, SNAKE1_COLOR, ALPHA_MASK,   ALPHA_MASK   },
    { ALPHA_MASK,   ALPHA_MASK,   ALPHA_MASK,   SNAKE1_COLOR, SNAKE1_COLOR, ALPHA_MASK,   ALPHA_MASK,   ALPHA_MASK   },
    { ALPHA_MASK,   ALPHA_MASK,   ALPHA_MASK,   SNAKE1_COLOR, SNAKE1_COLOR, ALPHA_MASK,   ALPHA_MASK,   ALPHA_MASK   }
};

static const uint16_t texture_head_snake2[TEXTURE_SIZE_X][TEXTURE_SIZE_Y] = {  

    { ALPHA_MASK,   ALPHA_MASK,   ALPHA_MASK,   TONGUE_COLOR, ALPHA_MASK,   ALPHA_MASK,   ALPHA_MASK,   ALPHA_MASK   },
    { ALPHA_MASK,   ALPHA_MASK,   ALPHA_MASK,   ALPHA_MASK,   TONGUE_COLOR, ALPHA_MASK,   ALPHA_MASK,   ALPHA_MASK   },
    { ALPHA_MASK,   SNAKE2_COLOR, EYE_COLOR,    TONGUE_COLOR, SNAKE2_COLOR, EYE_COLOR,    SNAKE2_COLOR, ALPHA_MASK   },
    { ALPHA_MASK,   SNAKE2_COLOR, EYE_COLOR,    SNAKE2_COLOR, TONGUE_COLOR, EYE_COLOR,    SNAKE2_COLOR, ALPHA_MASK   },
    { SNAKE2_COLOR, SNAKE2_COLOR, EYE_COLOR,    SNAKE2_COLOR, SNAKE2_COLOR, EYE_COLOR,    SNAKE2_COLOR, SNAKE2_COLOR },
    { SNAKE2_COLOR, SNAKE2_COLOR, SNAKE2_COLOR, SNAKE2_COLOR, SNAKE2_COLOR, SNAKE2_COLOR, SNAKE2_COLOR, SNAKE2_COLOR },
    { SNAKE2_COLOR, SNAKE2_COLOR, SNAKE2_COLOR, SNAKE2_COLOR, SNAKE2_COLOR, SNAKE2_COLOR, SNAKE2_COLOR, SNAKE2_COLOR },
    { SNAKE2_COLOR, SNAKE2_COLOR, SNAKE2_COLOR, SNAKE2_COLOR, SNAKE2_COLOR, SNAKE2_COLOR, SNAKE2_COLOR, SNAKE2_COLOR }
};

static const uint16_t texture_body_snake2[TEXTURE_SIZE_X][TEXTURE_SIZE_Y] = {  

    { ALPHA_MASK,   SNAKE2_COLOR, SNAKE2_COLOR, SNAKE2_COLOR, SNAKE2_COLOR, SNAKE2_COLOR, SNAKE2_COLOR, ALPHA_MASK   },
    { ALPHA_MASK,   SNAKE2_COLOR, SNAKE2_COLOR, SNAKE2_COLOR, SNAKE2_COLOR, SNAKE2_COLOR, SNAKE2_COLOR, ALPHA_MASK   },
    { ALPHA_MASK,   ALPHA_MASK,   SNAKE2_COLOR, SNAKE2_COLOR, SNAKE2_COLOR, SNAKE2_COLOR, SNAKE2_COLOR, SNAKE2_COLOR },
    { ALPHA_MASK,   ALPHA_MASK,   SNAKE2_COLOR, SNAKE2_COLOR, SNAKE2_COLOR, SNAKE2_COLOR, SNAKE2_COLOR, SNAKE2_COLOR },
    { ALPHA_MASK,   SNAKE2_COLOR, SNAKE2_COLOR, SNAKE2_COLOR, SNAKE2_COLOR, SNAKE2_COLOR, SNAKE2_COLOR, ALPHA_MASK   },
    { ALPHA_MASK,   SNAKE2_COLOR, SNAKE2_COLOR, SNAKE2_COLOR, SNAKE2_COLOR, SNAKE2_COLOR, SNAKE2_COLOR, ALPHA_MASK   },
    { SNAKE2_COLOR, SNAKE2_COLOR, SNAKE2_COLOR, SNAKE2_COLOR, SNAKE2_COLOR, SNAKE2_COLOR, ALPHA_MASK,   ALPHA_MASK   },
    { SNAKE2_COLOR, SNAKE2_COLOR, SNAKE2_COLOR, SNAKE2_COLOR, SNAKE2_COLOR, SNAKE2_COLOR, ALPHA_MASK,   ALPHA_MASK   }
};

static const uint16_t texture_twist1_snake2[TEXTURE_SIZE_X][TEXTURE_SIZE_Y] = {  
    { ALPHA_MASK,   ALPHA_MASK,   ALPHA_MASK,   ALPHA_MASK,   ALPHA_MASK,   ALPHA_MASK,   SNAKE2_COLOR, SNAKE2_COLOR },
    { ALPHA_MASK,   ALPHA_MASK,   ALPHA_MASK,   ALPHA_MASK,   ALPHA_MASK,   SNAKE2_COLOR, SNAKE2_COLOR, SNAKE2_COLOR },
    { ALPHA_MASK,   ALPHA_MASK,   ALPHA_MASK,   ALPHA_MASK,   SNAKE2_COLOR, SNAKE2_COLOR, SNAKE2_COLOR, SNAKE2_COLOR },
    { ALPHA_MASK,   ALPHA_MASK,   ALPHA_MASK,   SNAKE2_COLOR, SNAKE2_COLOR, SNAKE2_COLOR, SNAKE2_COLOR, SNAKE2_COLOR },
    { ALPHA_MASK,   ALPHA_MASK,   SNAKE2_COLOR, SNAKE2_COLOR, SNAKE2_COLOR, SNAKE2_COLOR, SNAKE2_COLOR, SNAKE2_COLOR },
    { ALPHA_MASK,   SNAKE2_COLOR, SNAKE2_COLOR, SNAKE2_COLOR, SNAKE2_COLOR, SNAKE2_COLOR, SNAKE2_COLOR, SNAKE2_COLOR },
    { SNAKE2_COLOR, SNAKE2_COLOR, SNAKE2_COLOR, SNAKE2_COLOR, SNAKE2_COLOR, SNAKE2_COLOR, SNAKE2_COLOR, ALPHA_MASK   },
    { SNAKE2_COLOR, SNAKE2_COLOR, SNAKE2_COLOR, SNAKE2_COLOR, SNAKE2_COLOR, SNAKE2_COLOR, SNAKE2_COLOR, ALPHA_MASK   }
};

static const uint16_t texture_twist2_snake2[TEXTURE_SIZE_X][TEXTURE_SIZE_Y] = {  
    { ALPHA_MASK,   SNAKE2_COLOR, ALPHA_MASK,   ALPHA_MASK,   ALPHA_MASK,   ALPHA_MASK,   ALPHA_MASK,   ALPHA_MASK   },
    { SNAKE2_COLOR, SNAKE2_COLOR, SNAKE2_COLOR, ALPHA_MASK,   ALPHA_MASK,   ALPHA_MASK,   ALPHA_MASK,   ALPHA_MASK   },
    { SNAKE2_COLOR, SNAKE2_COLOR, SNAKE2_COLOR, SNAKE2_COLOR, ALPHA_MASK,   ALPHA_MASK,   ALPHA_MASK,   ALPHA_MASK   },
    { SNAKE2_COLOR, SNAKE2_COLOR, SNAKE2_COLOR, SNAKE2_COLOR, SNAKE2_COLOR, ALPHA_MASK,   ALPHA_MASK,   ALPHA_MASK   },
    { SNAKE2_COLOR, SNAKE2_COLOR, SNAKE2_COLOR, SNAKE2_COLOR, SNAKE2_COLOR, SNAKE2_COLOR, ALPHA_MASK,   ALPHA_MASK   },
    { SNAKE2_COLOR, SNAKE2_COLOR, SNAKE2_COLOR, SNAKE2_COLOR, SNAKE2_COLOR, SNAKE2_COLOR, SNAKE2_COLOR, ALPHA_MASK   },
    { SNAKE2_COLOR, SNAKE2_COLOR, SNAKE2_COLOR, SNAKE2_COLOR, SNAKE2_COLOR, SNAKE2_COLOR, SNAKE2_COLOR, ALPHA_MASK   },
    { SNAKE2_COLOR, SNAKE2_COLOR, SNAKE2_COLOR, SNAKE2_COLOR, SNAKE2_COLOR, SNAKE2_COLOR, ALPHA_MASK,   ALPHA_MASK   }
};

static const uint16_t texture_tail_snake2[TEXTURE_SIZE_X][TEXTURE_SIZE_Y] = {  

    { SNAKE2_COLOR, SNAKE2_COLOR, SNAKE2_COLOR, SNAKE2_COLOR, SNAKE2_COLOR, SNAKE2_COLOR, SNAKE2_COLOR, SNAKE2_COLOR },
    { SNAKE2_COLOR, SNAKE2_COLOR, SNAKE2_COLOR, SNAKE2_COLOR, SNAKE2_COLOR, SNAKE2_COLOR, SNAKE2_COLOR, SNAKE2_COLOR },
    { ALPHA_MASK,   SNAKE2_COLOR, SNAKE2_COLOR, SNAKE2_COLOR, SNAKE2_COLOR, SNAKE2_COLOR, SNAKE2_COLOR, ALPHA_MASK   },
    { ALPHA_MASK,   SNAKE2_COLOR, SNAKE2_COLOR, SNAKE2_COLOR, SNAKE2_COLOR, SNAKE2_COLOR, SNAKE2_COLOR, ALPHA_MASK   },
    { ALPHA_MASK,   ALPHA_MASK,   SNAKE2_COLOR, SNAKE2_COLOR, SNAKE2_COLOR, SNAKE2_COLOR, ALPHA_MASK,   ALPHA_MASK   },
    { ALPHA_MASK,   ALPHA_MASK,   SNAKE2_COLOR, SNAKE2_COLOR, SNAKE2_COLOR, SNAKE2_COLOR, ALPHA_MASK,   ALPHA_MASK   },
    { ALPHA_MASK,   ALPHA_MASK,   ALPHA_MASK,   SNAKE2_COLOR, SNAKE2_COLOR, ALPHA_MASK,   ALPHA_MASK,   ALPHA_MASK   },
    { ALPHA_MASK,   ALPHA_MASK,   ALPHA_MASK,   SNAKE2_COLOR, SNAKE2_COLOR, ALPHA_MASK,   ALPHA_MASK,   ALPHA_MASK   }
};

static const uint16_t texture_apple[TEXTURE_SIZE_X][TEXTURE_SIZE_Y] = {  

    { ALPHA_MASK,   POINTS_COLOR, POINTS_COLOR, POINTS_COLOR, POINTS_COLOR, POINTS_COLOR, POINTS_COLOR, ALPHA_MASK   },
    { POINTS_COLOR, POINTS_COLOR, POINTS_COLOR, POINTS_COLOR, POINTS_COLOR, POINTS_COLOR, POINTS_COLOR, POINTS_COLOR },
    { POINTS_COLOR, POINTS_COLOR, POINTS_COLOR, POINTS_COLOR, POINTS_COLOR, POINTS_COLOR, POINTS_COLOR, POINTS_COLOR },
    { POINTS_COLOR, POINTS_COLOR, POINTS_COLOR, POINTS_COLOR, POINTS_COLOR, POINTS_COLOR, POINTS_COLOR, POINTS_COLOR },
    { POINTS_COLOR, POINTS_COLOR, POINTS_COLOR, POINTS_COLOR, POINTS_COLOR, POINTS_COLOR, POINTS_COLOR, POINTS_COLOR },
    { POINTS_COLOR, POINTS_COLOR, POINTS_COLOR, POINTS_COLOR, POINTS_COLOR, POINTS_COLOR, POINTS_COLOR, POINTS_COLOR },
    { POINTS_COLOR, POINTS_COLOR, POINTS_COLOR, POINTS_COLOR, POINTS_COLOR, POINTS_COLOR, POINTS_COLOR, POINTS_COLOR },
    { ALPHA_MASK,   POINTS_COLOR, POINTS_COLOR, POINTS_COLOR, POINTS_COLOR, POINTS_COLOR, POINTS_COLOR, ALPHA_MASK   }
};


int snake(int argc, char** argv);

